### PR TITLE
Update Bot Channel Registration uri automatically when debugging using NGROK

### PR DESCRIPTION
**Pull request by MTCMarkFranco**
works in both Windows Command & Linux shells.

### CODE REVIEW

**Comment by wictorwilen** [comment]
This is a great addition! Thanks a bunch!

However I would like to delay the merge of this PR and have it as one of the prime examples of the new build system (#107) that is in the plans/work. It would be fantastic to have this as either one of the core build plugins or a community plugin.

One thing I do think we should change for this as well, is the configuration - not have them in the standard `.env` file and instead in a dedicated settings file for this? (what I really want with ngrok settings as well)

Thoughts?

**Comment by andrewconnell** [comment]
While a cool addition, please reconsider adding this to the default project. It complicates the setup to do debugging... anyone with a commercial ngrok account doesn't need this... and it can turn away the brand new dev.

I'd recommend either providing this a documentation on how to do it OR as a flag on the generator to add it OR (not ideal) as a question if they want to add it when creating a project.

IMHO, you want to have the least friction to someone doing the equivalent "File => New Project => F5 => see it work". This seems to go against that mindset.

**Comment by wictorwilen** [comment]
@andrewconnell - agreed, hence my comments on having it as a module (preferably a community add-on) that is opt-in

**Comment by MTCMarkFranco** [comment]
Agreed on both points. extra setup after the generator has run will add further complexity. I think hanging it off the generator would make more sense as well.

**Comment by wictorwilen** [comment]
@MTCMarkFranco - I will add this feature as a separate build package to V3 of yo teams - working package name (`yoteams-build-ngrok`). So as a dev you will only have to do an additional step of `npm install yoteams-build-ngrok --save-dev`. Does that make sense?

Update: actually, this has nothing to do with ngrok really and should be names something like `yoteams-build-azure`? That way we can add similar "bonus" features to that package going forward?

**Comment by RickVanRousselt** [comment]
Closing this one due to inactivity. 
@MTCMarkFranco Please create a discussion around this, so that we can discuss this further. It's a nice feature, but indeed not for all to use. Wictor's idea of a community plugin might be the correct way forward.

**Pull request closed without merging**
