### PR TITLE
Added Support for Adaptive Card 1.4 version

### LINKED ISSUE #226: Support for Adaptive Card 1.4 version
**Is your feature request related to a problem? Please describe.**
Create applications with adaptive cards for [user specific views](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/user-specific-views?tabs=mobile).

**Describe the solution you'd like**
I tried using Adaptive Card v1.4 with yo teams, but it does not render a button for action as `Action.Execute`

**Describe alternatives you've considered**
None

### PR DESCRIPTION
**Pull request by nanddeepn**
Teams now supports v1.4 of Adaptive Cards.
The generated messaging extension is updated to use the 1.4 schema.

Fixes: #226

### CODE REVIEW

**Comment by nanddeepn** [comment]
Hi @wictorwilen 
I understand, just this number change is not enough. I am figuring out on how to handle the `Action.Execute` event.

**Comment by wictorwilen** [comment]
Thanks @nanddeepn, this is a good start. But as you say in order to work with the new `Action.Execute` we need to catch the invoke event  to the bot (`adaptiveCard/action`). That's handled by a separate package and I will release a new drop of that one shortly: https://github.com/wictorwilen/botbuilder-teams-messagingextensions/issues/12

**Comment by nanddeepn** [comment]
Thank you @wictorwilen

**Comment by wictorwilen** [comment]
@nanddeepn - I've published a preview of the messaging extension middleware. Please try with `botbuilder-teams-messagingextension@1.8.0-preview` and the `onActionExecute` method.

**Comment by nanddeepn** [comment]
Thank you @wictorwilen 
I will test and update the Adaptive Card payload soon on this PR.

**Comment by nanddeepn** [comment]
Hi @wictorwilen 
Raised a PR with updated Adaptive Card payload for v1.4.

We are now covering the MessagingExtensions. We also need to cover `Bot` to handle the `Action.Execute` event. Please share your views.

**Comment by wictorwilen** [comment]
Thanks @nanddeepn - I've merged this locally and are testing it out as we speak. For the Bot to handle universal actions you just override the `handleAdaptiveCardAction` method in the bot class.

**Comment by nanddeepn** [comment]
Hi @wictorwilen 
Thank you. Got your point.

I had to upgrade to use `v4.13.6` of packages `botbuilder` and `botbuilder-dialogs` to make `handleAdaptiveCardAction` method work in the bot class. It is same for you too?

For some reason, the installed package does not have `handleAdaptiveCardAction` inside `teamsActivityHandler.ts`. But, I can see it [here](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/teamsActivityHandler.ts)

**Comment by nanddeepn** [comment]
Hi @wictorwilen 
It is possible for you to share your solution please? I am using `botbuilder-teams-messagingextension@1.8.0-preview`. 
However, unable to get to `onActionExecute` working. In my case, still `onSubmitAction` is invoked.

**Pull request merged**
